apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-invoke-svc
  labels:
    app: simulation-invoke-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-invoke-svc
  template:
    metadata:
      labels:
        app: simulation-invoke-svc
    spec:
      containers:
        - name: simulation-invoke-svc
          image: ghcr.io/flawmop/simulation-invoke-svc
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          volumeMounts:
            - name: simulation-invoke-config-volume
              mountPath: /workspace/config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.level.root=DEBUG"
            - name: SPRING_RABBITMQ_HOST
              value: portal-rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmqpassword
            - name: SPRING_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmquser
            - name: URL_APP_MANAGER
              value: http://app-manager:8080/
            - name: URL_RESULTS_SVC
              value: http://results-svc:9004/
      volumes:
        - name: simulation-invoke-config-volume
          configMap:
            name: simulation-invoke-config
